# Generated by Django 5.2.13 on 2026-04-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review_user_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='personal_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
