# Generated by Django 5.2.13 on 2026-04-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_favorite_personal_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='personal_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
