# Generated by Django 5.2.13 on 2026-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_favorite_personal_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="watch_later",
            field=models.BooleanField(default=False),
        ),
    ]
