# Generated by Django 5.2.13 on 2026-04-09 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_favorite_watch_later"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="watchlists", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("media_type", models.CharField(choices=[("movie", "Movie"), ("tv", "TV Show")], max_length=10)),
                ("tmdb_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("poster_url", models.URLField(blank=True, default="")),
                ("overview", models.TextField(blank=True, default="")),
                ("year", models.CharField(blank=True, default="", max_length=4)),
                ("rating", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("watchlist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="movies.watchlist")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="watchlist",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="unique_user_watchlist_name"),
        ),
        migrations.AddConstraint(
            model_name="watchlistitem",
            constraint=models.UniqueConstraint(fields=("watchlist", "media_type", "tmdb_id"), name="unique_watchlist_item"),
        ),
    ]
